name: Build and deploy documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # we install doxygen because otherwise CMake fails, but we use one fetched with wget because the
      # one fetched with apt is outdated and the styling is broken.

      - name: Install requirements
        run: sudo apt install doxygen

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: pip install -r docs/requirements.txt

      # - name: Fetch Doxygen
      #   run: wget https://www.doxygen.nl/files/doxygen-1.9.7.linux.bin.tar.gz
      #     && tar -xvzf ./doxygen-1.9.7.linux.bin.tar.gz
      #     && ln -s ./doxygen-1.9.7/bin/doxygen ${GITHUB_WORKSPACE}/doxygen

      - name: Build docs
        run: cmake . -B ${GITHUB_WORKSPACE}/build/ -DCMAKE_BUILD_TYPE=Release -DTHALLIUM_BUILD_DOCS=ON -DTHALLIUM_BUILD_LIB=OFF
          && cmake --build ${GITHUB_WORKSPACE}/build/
          && touch ${GITHUB_WORKSPACE}/build/docs/html/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build/docs/html
